# Generated by Django 2.2.10 on 2021-10-27 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RtuSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtu_id', models.IntegerField()),
                ('rtu_name', models.CharField(max_length=264)),
                ('rtu_location', models.CharField(max_length=264)),
                ('moist_threshold', models.FloatField()),
                ('wet_threshold', models.FloatField()),
                ('min_tag_read', models.IntegerField()),
                ('average', models.IntegerField()),
                ('data_sampling_interval', models.IntegerField()),
                ('alarm', models.IntegerField()),
                ('reboot', models.IntegerField()),
                ('last_connected', models.DateTimeField(auto_now=True)),
                ('sent', models.IntegerField()),
                ('enabled', models.IntegerField()),
                ('status', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='SaveFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('layout', models.TextField(null=True)),
                ('device', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
