# Generated by Django 2.2.10 on 2021-10-27 02:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('timestamp', app.models.UnixTimestampField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('last_complete', app.models.UnixTimestampField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('time_completed', app.models.UnixTimestampField(null=True)),
            ],
        ),
    ]
