# Generated by Django 2.2.10 on 2021-10-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_processlist_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
