# Generated by Django 2.2.10 on 2021-10-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_variabledefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabledefault',
            name='process',
            field=models.CharField(default='aer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variabledefault',
            name='unit',
            field=models.CharField(default='L/min', max_length=10),
            preserve_default=False,
        ),
    ]
