# Generated by Django 2.2.10 on 2021-10-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211027_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlist',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
