# Generated by Django 2.2.10 on 2021-10-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_processlist_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
    ]
