# Generated by Django 2.2.10 on 2021-10-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_logdatatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('layout', models.TextField(null=True)),
            ],
        ),
    ]
