# Generated by Django 2.2.10 on 2021-10-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_processlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabledefault',
            name='value_set',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
