# Generated by Django 2.2.10 on 2021-10-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_variabledefault_value_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabledefault',
            name='prompt',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
