# Generated by Django 2.2.10 on 2021-10-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_variabledefault_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabledefault',
            name='check',
            field=models.CharField(default='true', max_length=100),
            preserve_default=False,
        ),
    ]
