# Generated by Django 2.2.10 on 2021-11-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_variabledefault_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdata',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='logdata',
            name='value',
        ),
        migrations.AddField(
            model_name='logdata',
            name='flow',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='flow_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='heater_set',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='heater_set_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='pressure',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='pressure_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='temperature',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='temperature_unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
