# Generated by Django 2.2.10 on 2021-11-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_report_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabledefault',
            name='enable_set',
            field=models.CharField(default='true', max_length=100),
            preserve_default=False,
        ),
    ]
