# Generated by Django 2.2.10 on 2021-11-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_variabledefault_enable_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('set_point', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
