# Generated by Django 2.2.10 on 2021-11-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sensorreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='set_point',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
