# Generated by Django 2.2.10 on 2021-11-25 02:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211124_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('percentage', models.DecimalField(decimal_places=1, max_digits=3)),
                ('timestamp', app.models.UnixTimestampField(null=True)),
            ],
        ),
    ]
