# Generated by Django 2.2.10 on 2022-02-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
